# Generated by Django 3.2 on 2021-05-16 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nessues_Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=21, unique=True)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=21)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=32, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=21)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nessues_app.nessues_group')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nessues_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=120)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_by', models.IntegerField(default=None, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nessues_app.table')),
            ],
        ),
        migrations.CreateModel(
            name='Nessues_Group_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.IntegerField(default=None)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nessues_app.nessues_group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nessues_group',
            name='users',
            field=models.ManyToManyField(through='nessues_app.Nessues_Group_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
